services:
  DockerImageDownloader:
    image: library/node:24.5
    container_name: DockerImageDownloader
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
      - ${CERT}:/etc/pki/tls/certs/auth.crt
      - ${KEY}:/etc/pki/tls/private/auth.key
    ports:
      - "${PORT}:3000"
    command: sh -c "npm install && npm run dev"
    restart: always