services:
  artifactfetcher:
    build:
      context: .
      target: base
    container_name: ArtifactFetcher_develop
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
      - ${CERT}:/etc/pki/tls/certs/auth.crt
      - ${KEY}:/etc/pki/tls/private/auth.key
    ports:
      - "${PORT}:3000"
    command: |
      sh -lc "
        (npm ci || npm install) && npm run dev
      "
    restart: unless-stopped