services:
  ArtifactFetcher:
    image: gariton/artifactfetcher:${IMAGE_TAG:-latest}
    container_name: ArtifactFetcher_production
    tty: true
    ports:
      - "${PORT}:${PORT}"
    env_file: ./.env
    restart: always
