services:
  DockerImageDownloader:
    image: library/node:24.5
    container_name: DockerImageDownloader
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "${PORT}:3000"
    command: sh -c "npm install && npm run build && npm run start"
    restart: always